places = ['Delhi', 'Mumbai', 'Lonavala', 'Bangalore', 'Hyderabad', 'Kolkata', 'Goa', 
 'Ahmedabad', 'Dwarka', 'Junagadh', 'Bhuj', 'Vadodara', 'Somnath', 'Rann of Kutch', 
 'Kevadia', 'Gandhinagar', 'Jaipur', 'Udaipur', 'Jaisalmer', 'Sawai Madhopur', 'Pushkar', 
 'Ajmer', 'Jodhpur', 'Chittorgarh', 'Mount Abu', 'Bikaner', 'Amritsar', 'Chandigarh', 
 'Alappuzha', 'Munnar', 'Kochi', 'Thiruvananthapuram', 'Kozhikode', 'Wayanad', 'Thekkady', 
 'Kumarakom', 'Varkala', 'Bekal', 'Kovalam', 'Kannur', 'Nelliyampathy', 'Mysore', 'Hampi', 
 'Coorg', 'Gokarna', 'Chikmagalur', 'Badami', 'Shivamogga', 'Mangalore', 'Murudeshwar', 
 'Bijapur', 'Bandipur', 'Halebidu', 'Pune', 'Aurangabad', 'Nashik', 'Shirdi', 'Alibaug', 
 'Ratnagiri', 'Nagpur', 'Kolhapur', 'Tarkarli', 'Satara', 'Matheran', 'Ajanta', 'Khajuraho', 
 'Bhopal', 'Indore', 'Gwalior', 'Ujjain', 'Jabalpur', 'Pachmarhi', 'Kanha', 'Bandhavgarh', 
 'Orchha', 'Mandu', 'Bhimbetka', 'Amarkantak', 'Chitrakoot', 'Shimla', 'Manali', 'dalhousie', 
 'Dalhousie', 'Spiti Valley', 'Kullu', 'Chamba', 'Kinnaur', 'Kangra', 'Palampur', 'Mandi', 
 'Bir Billing', 'McLeod Ganj', 'Manikaran', 'Narkanda', 'Barot', 'Shoja', 'Kufri', 'Nainital', 
 'Rishikesh', 'Haridwar', 'Dehradun', 'Mussoorie', 'Auli', 'Badrinath', 'Almora', 'Ranikhet', 
 'Jim Corbett', 'Uttarkashi', 'Chopta', 'Joshimath', 'Agra', 'Varanasi', 'Lucknow', 'Mathura', 
 'Ayodhya', 'Vrindavan', 'Allahabad', 'Jhansi', 'Sarnath', 'Fatehpur Sikri', 'Noida', 'Aligarh', 
 'Meerut', 'Kanpur', 'Srinagar', 'Leh', 'Pahalgam', 'Jammu', 'Udhampur', 'Anantnag', 'Nubra Valley', 
 'Kargil', 'Diskit', 'Kishtwar', 'Hemis', 'Dras', 'Porbandar', 'Darjeeling', 'Siliguri', 'Sundarbans', 
 'Digha', 'Murshidabad', 'Bolpur', 'Hooghly', 'Jalpaiguri', 'Cooch Behar', 'Purulia', 'Puri', 'Konark', 
 'Bhubaneswar', 'Rourkela', 'Cuttack', 'Sambalpur', 'Chilika', 'Berhampur', 'Keonjhar', 'Balasore', 
 'Kendujhar', 'Chennai', 'Madurai', 'Rameswaram', 'Kanyakumari', 'Ooty', 'Coimbatore', 'Kodaikanal', 
 'Thanjavur', 'Mahabalipuram', 'Yercaud', 'Tirunelveli', 'Chidambaram', 'Vijayawada', 'Visakhapatnam', 
 'Srisailam', 'Rajahmundry', 'Anantapur', 'Kurnool', 'Amravati', 'Guntur', 'Kadapa', 'Puttaparthi', 
 'Vizianagaram', 'Gangtok', 'Pelling', 'Namchi', 'Ravangla', 'Guwahati', 'Kaziranga', 'Sivasagar', 'Majuli', 
 'Manas', 'Hajo', 'Tawang', 'Agartala', 'Dumboor', 'Unakoti', 'Bastar', 'Dzükou Valley', 'Puducherry', 
 'Auroville', 'Port Blair', 'Havelock Island', 'Neil Island', 'Baratang Island', 'Diu', 'Deoghar', 'Ranchi', 
 'Bodh Gaya', 'Patna', 'Gurugram', 'New Delhi', 'Kedarnath', 'Greater Noida', 'Bengaluru', 'Cherrapunji']

places.sort()
print(places)
